name: Backporting meta-data
description: Inputs and outputs for the backporting action
inputs:
  repoName:  # id of input
    description: Repo name
    required: true
  
  pr_url:
    description: PR comment URL
    required: true

  access_token: #id of input
    description: Github access token
    required: true
  
  branches:
    description: Branches you want to backport to
    required: true

  commitSha:
    description: Commit sha to be cheery picked
    required: true

  commentTime:
    description: Time at which comment was made

runs:
  using: 'docker'
  image: 'Dockerfile'

  env:
    NAME: ${{ inputs.repoName }}
    ACCESS_TOKEN: ${{inputs.access_token}}
    BRANCH: ${{inputs.branches}}
    COMMIT_SHA: ${{inputs.commitSha}}
    PR_URL: ${{inputs.pr_url}}
    COMMENTTIME: ${{inputs.commentTime}}
