name: Webhook Example
on: repository_dispatch
jobs:
  Backport:
    runs-on: ubuntu-latest
    steps:
    - name: Getting the from the comment
      run: |
        branch=$(echo ${{github.event.client_payload.comment.body}} | cut -d ' ' -f 3)
        echo ::set-env name=branchName::$branch
        echo ::set-env name=time::${{github.event.client_payload.comment.created_at}}

    - name: Checking out repo
      if: github.event.action == 'issue_comment'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_PAT }}
        repository: ${{github.event.client_payload.repository.full_name}}
        ref: master

    - name: Backporting
      id: backporting
      uses: TestOrgWeb/infra/actions@master
      with:
        repoName: ${{github.event.client_payload.repository.full_name}}
        PR: ${{github.event.client_payload.issue.pull_request.url}}
        comment_url: ${{github.event.client_payload.issue.comments_url}}
        access_token: ${{ secrets.MY_PAT }}
        branches: ${{ env.branchName}}
        commitSha: ${{env.commitsha}}
        commentTime: ${{env.time}}


